### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/starter-snake-python#4]
**What's the problem?**
This repo currently uses Python2.7, which has been officially end-of-life'd. New developers are most likely to be learning and using Python3, which can cause problems when developing a Python2.7 starter snake.

**What's the solution?**
We'd like to move this repo to use Python3 by default.

**Other requirements?**
* It must still work on Heroku by default.
* It does not have to be backward compatible with Python2.7

**Comment by bvanvugt** [comment]
@JosephTLucas has submitted
https://github.com/BattlesnakeOfficial/starter-snake-python/pull/2
which moves to Python 3.7.5

@jonknoll has submitted
https://github.com/BattlesnakeOfficial/starter-snake-python/pull/3
which moves to Python 3.8.1

**Comment by jonknoll** [comment]
New pull request(s) submitted which update to 3.7.6, which is as high as the gevent library supports. Tested locally and on Heroku.

**Comment by bvanvugt** [comment]
Combined our ideas with @jonknoll's PR into #12. Resolving.
